server:
  port: 8080 

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-145-110-118.compute-1.amazonaws.com:5432/d6pto059vhp5te
    username: ittvznmdsodqdv
    password: a2bbb444887cbb2b981eba48eccc89d69c39072fb27d4ab7d9ae031f0f0d3c4d